app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['prefix' => 'telegram/76A6AF868DB16F'], function () {

  // Matches The "/telegram/first" URL
  Route::post('first', [
//    'middleware' => ['telegram_analysis'],
    'uses' => 'BotController@index'
  ]);
  Route::get('first', 'BotController@index');

  Route::get('webhook/{action}', [
    'middleware' => ['has_perm:_superadmin'],
    'uses'       => 'BotController@webhook',
  ]);
});
Route::get('test', 'BotController@test');
Route::group(['prefix' => 'telegram/76A6AF868DB16'], function () {

  // Matches The "/telegram/first" URL
  Route::post('first', [
//    'middleware' => ['telegram_analysis'],
'uses' => 'BotController@index'
  ]);
  Route::get('first', 'BotController@index');

  Route::get('webhook/{action}', [
   'middleware' => ['has_perm:_superadmin'],
   'uses'       => 'BotController@webhook',
  ]);
});

// super admin and bot-admin routes.
Route::group([
  'prefix'     => 'admin',
  'middleware' => ['has_perm:_superadmin,_bot-admin'],
], function () {
  Route::resource('states.questions', 'QuestionsController');
  Route::resource('states.questions.answers', 'AnswersController');
  Route::resource('results', 'EndResultController');
  Route::get('admin/results/{age}', 'EndResultController@resultsOnAge');
  Route::resource('results.products', 'RelatedProductsController');

  // ordering
  Route::post('questions/order', [
    'as'   => 'admin.states.questions.order',
    'uses' => 'QuestionsController@weightOrder',
  ]);
  Route::post('questions/answers/order', [
    'as'   => 'admin.questions.answers.order',
    'uses' => 'AnswersController@weightOrder',
  ]);
  Route::post('results/products/order', [
    'as'   => 'admin.results.products.order',
    'uses' => 'RelatedProductsController@weightOrder',
  ]);

  // tables for search and send message to users.
  Route::get('bot-actions/broadcast-message', ['as' => 'bot.action.index', 'uses' => 'BotActions@broadCastMessage']);
  Route::post('bot-actions/broadcast-message', ['as' => 'bot.action.sendMessage', 'uses' => 'BotActions@sendMessage']);
  // logs
  Route::get('bot-logs/', ['as' => 'bot.action.sendMessage', 'uses' => 'BotActions@sendMessage']);
});

// super admin routes.
Route::group([
  'prefix'     => 'admin',
  'middleware' => ['has_perm:_superadmin'],
], function () {
  Route::resource('states', 'StatesController');
  Route::resource('state-groups', 'StateGroupsController');
  Route::post('state-groups/add/state', 'StateGroupsController@stateStore');
  Route::get('state-groups/{state_groups}/state/create', 'StatesController@create')->name('admin.state_groups.states.create');;
  Route::post('state-groups/{state_groups}/state/create', 'StatesController@store')->name('admin.state_groups.states.store');;
  /*
  |--------------------------------------------------------------------------
  | Application Logs
  |--------------------------------------------------------------------------
  */
  Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});

Route::group([
  'prefix'     => 'api/v1',
  'middleware' => ['has_perm:_superadmin,_bot-admin'],
], function () {
  // Angular search
  Route::post('search/main-search/{query?}', 'SearchController@mainSearch');
  Route::post('search/index', 'SearchController@index');
//  Route::post('search/index', 'SearchController@index');
});

Route::get('admin/test', function(){
  $customer_id = 2;
  $currentState = \App\CurrentState::findCurrentState(65817282);

  return $currentState;
  $answeredQuestions = \App\AnsweredQuestion::where('customer_id', 126506089)->where('closed', 0)->pluck('answer_id');

  $answers = \App\Answer::whereIn('id', $answeredQuestions)->get();

  $result = 0;
  foreach ($answers as $answer) {
    dump($answer->id);
    dump($answer->getMeta('point'));
//        Log::info($answer);
    $result += $answer->getMeta('point');
  }
  dd($result);
});

app/StateGroup.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class StateGroup extends Model {
  public $fillable = [
    'name',
  ];
  
  public function states() {
    return $this->belongsToMany('App\State', 'state_group_state');
  }
}

app/StateGroups.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class StateGroups extends Model
{
    //
}

app/Http/Controllers/StateGroupsController.php
<?php

namespace App\Http\Controllers;

use App\State;
use App\StateGroup;
use App\StateGroupState;
use Illuminate\Http\Request;
use Kris\LaravelFormBuilder\FormBuilder as KFB;

use App\Http\Requests;

class StateGroupsController extends Controller {
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   * @internal param \App\StateGroup $state_groups
   *
   */
  public function index() {
    // list all state groups
    $state_groups = StateGroup::All();

    $states = State::whereNotIn('id', StateGroupState::all()->pluck('state_id')->toArray())->get();

    return view('admin.state_groups.list', compact('state_groups', 'states'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @param \Kris\LaravelFormBuilder\FormBuilder $formBuilder
   *
   * @return \Illuminate\Http\Response
   */
  public function create(KFB $formBuilder) {
    //
    $form = $formBuilder->create('App\Forms\StateGroupForm', [
      'method' => 'POST',
      'url'    => route('admin.state-groups.store'),
    ]);

    return view('admin.state_groups.create', compact('form'));
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request $request
   *
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request) {
    StateGroup::create($request->all());

    return redirect()->route('admin.state-groups.index');
  }

  /**
   * Display the specified resource.
   *
   * @param \App\StateGroup $state_group
   *
   * @return \Illuminate\Http\Response
   * @internal param \App\StateGroup $state_groups
   *
   * @internal param int $id
   */
  public function show(StateGroup $state_group) {
    $all_states = State::whereNotIn('id', $state_group->states->pluck('id'))->pluck('name', 'id');

    return view('admin.states.ungroup-list', ['states'      => $state_group->states,
                                      'state_group' => $state_group,
                                      'all_states' => $all_states,
    ]);
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param KFB $formBuilder
   * @return \Illuminate\Http\Response
   * @internal param int $id
   *
   */
  public function edit(KFB $formBuilder) {
    //
    $form = $formBuilder->create('App\Forms\StateGroupForm', [
     'method' => 'POST',
     'url'    => route('admin.state-groups.store'),
    ]);

    return view('admin.state_groups.create', compact('form'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request $request
   * @param  int                      $id
   *
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, $id) {
    //
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param \App\StateGroup $state_groups
   *
   * @return \Illuminate\Http\Response
   * @internal param int $id
   *
   */
  public function destroy(StateGroup $state_groups) {
    StateGroupState::where('state_group_id', $state_groups->id)->delete();
    return StateGroup::destroy($state_groups->id);
  }

  public function stateStore(Request $request) {
    return StateGroupState::create($request->all());
  }
}

resources/views/admin/state_groups/create.blade.php
@extends('admin.default')

@section('content')
    <div class="main-content" autoscroll="true" bs-affix-target="" init-ripples="" style="">
        <div class="col-md-10 col-md-push-1">
            <div class="well white">
                {!! form($form) !!}
            </div>
            <a href="{{ route('admin.state-groups.index') }}" class="btn btn-lg btn-round btn-primary pull-left">
                <span class="md md-keyboard-arrow-left"></span>
            </a>
        </div>
    </div>
@endsection

resources/views/admin/state_groups/list.blade.php
@extends('admin.default')

@section('content')
    <div class="main-content" autoscroll="true" bs-affix-target="" init-ripples="" style="">
        <section class="tables-data">
            <div class="page-header">
                <h1>
                    {{--<i class="md md-add-circle-outline"></i>--}}
                    <a href="{{route('admin.state-groups.create')}}" class="md md-add-circle-outline text-primary">افزودن گروه</a>
                </h1>
            </div>
            <div class="card">
                <div>
                    <div class="">
                        {!! Form::open(['route' => 'admin.states.questions.order']) !!}
                        <table class="table table-full table-full-small ">
                            <thead>
                            <tr>
                                <th>نام</th>
                                <th>تنظیمات</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($state_groups as $state_group)
                                <tr class="deletable">
                                    <td>{{ $state_group->name }}</td>
                                    <td>
                                        <a href="{{ route('admin.state-groups.edit', $state_group) }}"
                                           class="btn btn-lg btn-round btn-success">
                                            <span class="md md-mode-edit"></span>

                                            <div class="ripple-wrapper"></div>
                                        </a>
                                        <a href="{{ route('admin.state-groups.destroy', $state_group) }}"
                                           class="btn btn-lg btn-round btn-success item delete">
                                            <span class="md md-delete"></span>

                                            <div class="ripple-wrapper"></div>
                                        </a>
                                        <a href="{{ route('admin.state-groups.show', $state_group) }}"
                                           title="لیست حالت ها" class="btn btn-lg btn-round btn-info">
                                            <span class="md md-list"></span>

                                            <div class="ripple-wrapper"></div>
                                        </a>
                                        {!! Form::input('text', 'weight[]', $state_group->weight, ['class' => 'hidden weight']) !!}
                                        {!! Form::input('text', 'qid[]', $state_group->id, ['class' => 'hidden']) !!}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <section class="tables-data">
                <div class="page-header">
                    h2
                </div>
                <div class="card">
                    <div>
                        <div class="">
                            <table class="table table-full table-full-small" ng-controller="StateGroupController">
                                <thead>
                                <tr>
                                    <th>نام</th>
                                    <th>قابل جستجو</th>
                                    <th>رویداد در حین شروع مرحله</th>
                                    <th>تنظیمات</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($states as $state)
                                    <tr class="deletable">
                                        <td>{{ $state->name }}</td>
                                        <td>
                                            <div class="checkbox">
                                                <label>
                                                    <input type="checkbox" disabled {{$state->deletable ? 'checked' : ''}}>
                                                </label>
                                            </div>
                                        </td>
                                        <td>
                                            {{ $state->result_type }}
                                        </td>
                                        <td>
                                            <a href="{{ route('admin.states.edit', $state) }}"
                                               class="btn btn-lg btn-round btn-success">
                                                <span class="md md-mode-edit"></span>

                                                <div class="ripple-wrapper"></div>
                                            </a>
                                            <a href="{{ route('admin.states.destroy', $state) }}"
                                               class="btn btn-lg btn-round btn-success item delete">
                                                <span class="md md-delete"></span>

                                                <div class="ripple-wrapper"></div>
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </section>
        </section>
        <div class="footer-buttons">
            <a href="{{route('admin.state-groups.create')}}"
               class="btn btn-primary btn-round btn-lg" data-title="گروه جدید"
               data-toggle="tooltip" data-original-title="" title="">
                <i class="md md-add"></i>
            </a>
            {{--{!! Form::submit('Save', ['class' => 'btn btn-info btn-round btn-lg']) !!}--}}
        </div>
        {!! Form::close() !!}
    </div>
@endsection