app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['prefix' => 'telegram/76A6AF868DB16F'], function () {

  // Matches The "/telegram/first" URL
  Route::post('first', [
//    'middleware' => ['telegram_analysis'],
    'uses' => 'BotController@index'
  ]);
  Route::get('first', 'BotController@index');

  Route::get('webhook/{action}', [
    'middleware' => ['has_perm:_superadmin'],
    'uses'       => 'BotController@webhook',
  ]);
});
Route::get('test', 'BotController@test');
Route::group(['prefix' => 'telegram/76A6AF868DB16'], function () {

  // Matches The "/telegram/first" URL
  Route::post('first', [
//    'middleware' => ['telegram_analysis'],
'uses' => 'BotController@index'
  ]);
  Route::get('first', 'BotController@index');

  Route::get('webhook/{action}', [
   'middleware' => ['has_perm:_superadmin'],
   'uses'       => 'BotController@webhook',
  ]);
});

// super admin and bot-admin routes.
Route::group([
  'prefix'     => 'admin',
  'middleware' => ['has_perm:_superadmin,_bot-admin'],
], function () {
  Route::resource('states.questions', 'QuestionsController');
  Route::resource('states.questions.answers', 'AnswersController');
  Route::resource('results', 'EndResultController');
  Route::get('admin/results/{age}', 'EndResultController@resultsOnAge');
  Route::resource('results.products', 'RelatedProductsController');

  // ordering
  Route::post('questions/order', [
    'as'   => 'admin.states.questions.order',
    'uses' => 'QuestionsController@weightOrder',
  ]);
  Route::post('questions/answers/order', [
    'as'   => 'admin.questions.answers.order',
    'uses' => 'AnswersController@weightOrder',
  ]);
  Route::post('results/products/order', [
    'as'   => 'admin.results.products.order',
    'uses' => 'RelatedProductsController@weightOrder',
  ]);

  // tables for search and send message to users.
  Route::get('bot-actions/broadcast-message', ['as' => 'bot.action.index', 'uses' => 'BotActions@broadCastMessage']);
  Route::post('bot-actions/broadcast-message', ['as' => 'bot.action.sendMessage', 'uses' => 'BotActions@sendMessage']);
  // logs
  Route::get('bot-logs/', ['as' => 'bot.action.sendMessage', 'uses' => 'BotActions@sendMessage']);
});

// super admin routes.
Route::group([
  'prefix'     => 'admin',
  'middleware' => ['has_perm:_superadmin'],
], function () {
  Route::resource('states', 'StatesController');
  Route::resource('state-groups', 'StateGroupsController');
  Route::post('state-groups/add/state', 'StateGroupsController@stateStore');
  Route::get('state-groups/{state_groups}/state/create', 'StatesController@create')->name('admin.state_groups.states.create');;
  Route::post('state-groups/{state_groups}/state/create', 'StatesController@store')->name('admin.state_groups.states.store');;
  /*
  |--------------------------------------------------------------------------
  | Application Logs
  |--------------------------------------------------------------------------
  */
  Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});

Route::group([
  'prefix'     => 'api/v1',
  'middleware' => ['has_perm:_superadmin,_bot-admin'],
], function () {
  // Angular search
  Route::post('search/main-search/{query?}', 'SearchController@mainSearch');
  Route::post('search/index', 'SearchController@index');
//  Route::post('search/index', 'SearchController@index');
});

Route::get('admin/test', function(){
  $customer_id = 2;
  $currentState = \App\CurrentState::findCurrentState(65817282);

  return $currentState;
  $answeredQuestions = \App\AnsweredQuestion::where('customer_id', 126506089)->where('closed', 0)->pluck('answer_id');

  $answers = \App\Answer::whereIn('id', $answeredQuestions)->get();

  $result = 0;
  foreach ($answers as $answer) {
    dump($answer->id);
    dump($answer->getMeta('point'));
//        Log::info($answer);
    $result += $answer->getMeta('point');
  }
  dd($result);
});

app/State.php
<?php

namespace App;

use App\AnsweredQuestion;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Log;

class State extends Model
{

  /**
   * The attributes that are mass assignable.
   *
   * @var array
   */
  protected $fillable = [
   'name',
   'result_type',
   'next_state',
   'deletable',
  ];

  public function gender()
  {
    return $this->result_type == 'gender';
  }

  public function age()
  {
    return $this->result_type == 'age';
  }

  public function province()
  {
    return $this->result_type == 'province';
  }

  public function nextState($current_state, $not_ignore_next_state = true)
  {
    $state = State::find($current_state->current_state);
    if ($state->next_state && $not_ignore_next_state) {
      return self::find($state->next_state);
    };

    $answered_questions = AnsweredQuestion::with('answer')
     ->where('customer_id', $current_state->customer_id)
     ->whereIn('question_id', $this->questions->lists('id'))
     ->where('closed', 0)
     ->get();

    $next_state_ids = [];
    foreach ($answered_questions as $answered_question) {
      $next_state_ids[] = $answered_question->answer->next_state_id;
    }

    $counted_values = array_count_values($next_state_ids);
    $next_state_id = array_search(max($counted_values), $counted_values);

    return self::find($next_state_id);
  }

  public function prevState($state_id)
  {
    return self::find($state_id);
  }

  public function saveAnswer($answer_text, $question_id, $customer_id)
  {
//    $state    = self::find($this->current_state);
    $question = $this->questions()->find($question_id);
    if (!$question || !$question->save_answer) return;
    $answer = $question->answers()->ValidateAnswers($answer_text)->first();

    if(!$answer) {
      return;
    }

    AnsweredQuestion::create([
     'question_id' => $question_id,
     'answer_id'   => $answer->id,
     'customer_id' => $customer_id,
     'closed'      => 0,
    ])->save();
  }

  public function firstQuestion()
  {
    return $this->questions()->orderBy('weight')->first();
  }

  public function scopeLastQuestion()
  {
    return $this->questions()->orderBy('weight', 'desc')->first();
  }

  /**
   * A State can have many questions
   *
   * @return \Illuminate\Database\Eloquent\Relations\HasMany
   */
  public function questions()
  {
    return $this->hasMany('App\Question');
  }

  public function stateGroups()
  {
    return $this->belongsToMany('App\StateGroup', 'state_group_state');
  }
}

app/Http/Controllers/StatesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateStateRequest;
use App\State;
use App\StateGroupState;
use Collective\Html\FormBuilder;
use Illuminate\Http\Request;

use App\Http\Requests;
use Kris\LaravelFormBuilder\FormBuilder as KFB;

class StatesController extends Controller {
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index() {
    // list all states
    $states = State::paginate(15);

    return view('admin.states.list', compact('states'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @param \Kris\LaravelFormBuilder\FormBuilder $formBuilder
   *
   * @return \Illuminate\Http\Response
   */
  public function create(KFB $formBuilder, $state_groups = null) {
      //
      $form = $formBuilder->create('App\Forms\StateForm', [
        'method' => 'POST',
        'url'    => route('admin.state_groups.states.create', ['state_groups' => $state_groups->id]),
      ]);

      return view('admin.states.create', compact('form'));
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param \App\Http\Requests\CreateStateRequest|\Illuminate\Http\Request $request
   *
   * @param null                                                           $state_groups
   * @return \Illuminate\Http\Response
   * @internal param \Kris\LaravelFormBuilder\FormBuilder $formBuilder
   */
  public function store(Request $request, $state_groups = null) {
    try {
      \DB::transaction(function () use ($request, $state_groups) {
        $state = State::create($request->all());
        if($state_groups) {
          StateGroupState::create([
           'state_group_id' => $state_groups->id,
           'state_id' => $state->id,
          ]);
        }
      });
    }
    catch (\Exception $e) {
      return redirect()->back()->withErrors('لطفا دوباره تلاش نمایید');
    }

    return redirect()->back();
  }

  /**
   * Display the specified resource.
   *
   * @param \App\State $state
   *
   * @return \Illuminate\Http\Response
   * @internal param int $id
   */
  public function show(State $state) {
    return redirect()->back();
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param \App\State                                                        $state
   *
   * @param \Collective\Html\FormBuilder|\Kris\LaravelFormBuilder\FormBuilder $formBuilder
   *
   * @return \Illuminate\Http\Response
   * @internal param int $id
   */
  public function edit(State $state, KFB $formBuilder) {
    $form = $formBuilder->create('App\Forms\StateForm', [
      'method' => 'PATCH',
      'url'    => route('admin.states.update', $state),
      'model'  => $state,
    ]);

    $form->modify('submit', 'submit', [
      'label' => 'ویرایش',
    ]);

    return view('admin.states.create', compact('form'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param \App\Http\Requests\CreateStateRequest|\Illuminate\Http\Request $request
   * @param \App\State                                                     $state
   *
   * @return \Illuminate\Http\Response
   * @internal param int $id
   */
  public function update(CreateStateRequest $request, State $state) {
    $request = array_merge($request->all(), ['deletable' => $request->has('deletable') ? 1 : 0]);
    $state->update($request);

    return redirect()->route('admin.states.index');
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param \App\State $state
   *
   * @return \Illuminate\Http\Response
   * @internal param int $id
   *
   */
  public function destroy(State $state) {
    return State::destroy($state->id);
  }
}

resources/views/admin/states/create.blade.php
@extends('admin.default')

@section('content')
    <div class="main-content" autoscroll="true" bs-affix-target="" init-ripples="" style="">
        <div class="col-md-10 col-md-push-1">
            <div class="well white">
                {!! form($form) !!}
            </div>
            <a href="{{ URL::previous() }}" class="btn btn-lg btn-round btn-primary pull-left">
                <span class="md md-keyboard-arrow-left"></span>
            </a>
        </div>
    </div>
@endsection

resources/views/admin/states/list.blade.php
@extends('admin.default')

@section('content')
    <div class="main-content" autoscroll="true" bs-affix-target="" init-ripples="" style="">
        <section class="tables-data">
            <div class="card">
                <div>
                    <div class="">
                        <table class="table table-full table-full-small" ng-controller="StateGroupController">
                            <thead>
                            <tr>
                                <th>نام</th>
                                <th>قابل جستجو</th>
                                <th>رویداد در حین شروع مرحله</th>
                                <th>تنظیمات</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($states as $state)
                                <tr class="deletable">
                                    <td>{{ $state->name }}</td>
                                    <td>
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox" disabled {{$state->deletable ? 'checked' : ''}}>
                                            </label>
                                        </div>
                                    </td>
                                    <td>
                                        {{ $state->result_type }}
                                    </td>
                                    <td>
                                        <a href="{{ route('admin.states.edit', $state) }}"
                                           class="btn btn-lg btn-round btn-success">
                                            <span class="md md-mode-edit"></span>

                                            <div class="ripple-wrapper"></div>
                                        </a>
                                        <a href="{{ route('admin.states.destroy', $state) }}"
                                           class="btn btn-lg btn-round btn-success item delete">
                                            <span class="md md-delete"></span>

                                            <div class="ripple-wrapper"></div>
                                        </a>
                                        <a href="{{ route('admin.states.questions.index', $state) }}"
                                           class="btn btn-lg btn-round btn-info">
                                            <span class="md md-list"></span>
                                            <div class="ripple-wrapper"></div>
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
        <div class="footer-buttons">
            <a href="{{route('admin.states.create')}}"
               class="btn btn-primary btn-round btn-lg" data-title="حالت جدید"
               data-toggle="tooltip" data-original-title="" title="">
                <i class="md md-add"></i>
            </a>
        </div>
    </div>
        {{ $states->links() }}
@endsection

resources/views/admin/states/ungroup-list.blade.php
@extends('admin.default')

@section('content')
    <div class="main-content" autoscroll="true" bs-affix-target="" init-ripples="" style="">
        <section class="tables-data">
            <div class="page-header">
                <h1>لیست حالت های {{ $state_group->name }}</h1>
            </div>
            <div class="card">
                <div>
                    <div class="">
                        <table class="table table-full table-full-small" ng-controller="StateGroupController">
                            <thead>
                            <tr>
                                <th>نام</th>
                                <th>قابل جستجو</th>
                                <th>رویداد در حین شروع مرحله</th>
                                <th>تنظیمات</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($states as $state)
                                <tr class="deletable">
                                    <td>{{ $state->name }}</td>
                                    <td>
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox" disabled {{$state->deletable ? 'checked' : ''}}>
                                            </label>
                                        </div>
                                    </td>
                                    <td>
                                        {{ $state->result_type }}
                                    </td>
                                    <td>
                                        <a href="{{ route('admin.states.edit', $state) }}"
                                           class="btn btn-lg btn-round btn-success">
                                            <span class="md md-mode-edit"></span>

                                            <div class="ripple-wrapper"></div>
                                        </a>
                                        <a href="{{ route('admin.states.destroy', $state) }}"
                                           class="btn btn-lg btn-round btn-success item delete">
                                            <span class="md md-delete"></span>

                                            <div class="ripple-wrapper"></div>
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                            <tr>
                                <td>نام حالت</td>
                                <td colspan="2">
                                <span>
                                    {!! Form::select('size', $all_states, NULL, ['ng-model' => 'stateId', 'class' => 'form-control']) !!}
                                    <input type="hidden" ng-model="stateGroupId"
                                           ng-init="stateGroupId = {{ $state_group->id }}">
                                </span>
                                </td>
                                <td>
                                    <button
                                            class="btn btn-success" ng-click="state_group_add()">
                                        <span class="md md-add"></span>
                                        <span>افزودن</span>

                                        <div class="ripple-wrapper"></div>
                                    </button>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
        <div class="footer-buttons">
            <a href="{{route('admin.state_groups.states.create', ['state_groups' => $state_group->id])}}"
               class="btn btn-primary btn-round btn-lg" data-title="حالت جدید"
               data-toggle="tooltip" data-original-title="" title="">
                <i class="md md-add"></i>
            </a>
            <a href="{{ route('admin.state-groups.index') }}" class="btn btn-lg btn-round btn-success pull-left">
                <span class="md md-keyboard-arrow-left"></span>
            </a>
        </div>
    </div>
@endsection