app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['prefix' => 'telegram/76A6AF868DB16F'], function () {

  // Matches The "/telegram/first" URL
  Route::post('first', [
//    'middleware' => ['telegram_analysis'],
    'uses' => 'BotController@index'
  ]);
  Route::get('first', 'BotController@index');

  Route::get('webhook/{action}', [
    'middleware' => ['has_perm:_superadmin'],
    'uses'       => 'BotController@webhook',
  ]);
});
Route::get('test', 'BotController@test');
Route::group(['prefix' => 'telegram/76A6AF868DB16'], function () {

  // Matches The "/telegram/first" URL
  Route::post('first', [
//    'middleware' => ['telegram_analysis'],
'uses' => 'BotController@index'
  ]);
  Route::get('first', 'BotController@index');

  Route::get('webhook/{action}', [
   'middleware' => ['has_perm:_superadmin'],
   'uses'       => 'BotController@webhook',
  ]);
});

// super admin and bot-admin routes.
Route::group([
  'prefix'     => 'admin',
  'middleware' => ['has_perm:_superadmin,_bot-admin'],
], function () {
  Route::resource('states.questions', 'QuestionsController');
  Route::resource('states.questions.answers', 'AnswersController');
  Route::resource('results', 'EndResultController');
  Route::get('admin/results/{age}', 'EndResultController@resultsOnAge');
  Route::resource('results.products', 'RelatedProductsController');

  // ordering
  Route::post('questions/order', [
    'as'   => 'admin.states.questions.order',
    'uses' => 'QuestionsController@weightOrder',
  ]);
  Route::post('questions/answers/order', [
    'as'   => 'admin.questions.answers.order',
    'uses' => 'AnswersController@weightOrder',
  ]);
  Route::post('results/products/order', [
    'as'   => 'admin.results.products.order',
    'uses' => 'RelatedProductsController@weightOrder',
  ]);

  // tables for search and send message to users.
  Route::get('bot-actions/broadcast-message', ['as' => 'bot.action.index', 'uses' => 'BotActions@broadCastMessage']);
  Route::post('bot-actions/broadcast-message', ['as' => 'bot.action.sendMessage', 'uses' => 'BotActions@sendMessage']);
  // logs
  Route::get('bot-logs/', ['as' => 'bot.action.sendMessage', 'uses' => 'BotActions@sendMessage']);
});

// super admin routes.
Route::group([
  'prefix'     => 'admin',
  'middleware' => ['has_perm:_superadmin'],
], function () {
  Route::resource('states', 'StatesController');
  Route::resource('state-groups', 'StateGroupsController');
  Route::post('state-groups/add/state', 'StateGroupsController@stateStore');
  Route::get('state-groups/{state_groups}/state/create', 'StatesController@create')->name('admin.state_groups.states.create');;
  Route::post('state-groups/{state_groups}/state/create', 'StatesController@store')->name('admin.state_groups.states.store');;
  /*
  |--------------------------------------------------------------------------
  | Application Logs
  |--------------------------------------------------------------------------
  */
  Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});

Route::group([
  'prefix'     => 'api/v1',
  'middleware' => ['has_perm:_superadmin,_bot-admin'],
], function () {
  // Angular search
  Route::post('search/main-search/{query?}', 'SearchController@mainSearch');
  Route::post('search/index', 'SearchController@index');
//  Route::post('search/index', 'SearchController@index');
});

Route::get('admin/test', function(){
  $customer_id = 2;
  $currentState = \App\CurrentState::findCurrentState(65817282);

  return $currentState;
  $answeredQuestions = \App\AnsweredQuestion::where('customer_id', 126506089)->where('closed', 0)->pluck('answer_id');

  $answers = \App\Answer::whereIn('id', $answeredQuestions)->get();

  $result = 0;
  foreach ($answers as $answer) {
    dump($answer->id);
    dump($answer->getMeta('point'));
//        Log::info($answer);
    $result += $answer->getMeta('point');
  }
  dd($result);
});

app/EndResult.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EndResult extends Model {

  protected $fillable = [
    'body',
  ];

  public function tags() {
    return $this->hasMany('App\TagEndResult', 'end_result_id');
  }
  
  public function products() {
    return $this->hasMany('App\RelatedProduct', 'end_result_id');
  }
}

app/Http/Controllers/EndResultController.php
<?php

namespace App\Http\Controllers;

use App\Answer;
use App\CustomerEndResult;
use App\EndResult;
use App\Question;
use App\RelatedProduct;
use App\State;
use App\TagEndResult;
use Carbon\Carbon;
use App\Http\Requests;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\URL;
use Kris\LaravelFormBuilder\FormBuilder as KFB;

class EndResultController extends Controller {
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index() {
    $answers = State::where('result_type', 'age')->first()->questions()->first()->answers()->orderBy('body')->get();

    return view('admin.end_results.group-list', compact('answers'));
  }

  public function resultsOnAge($age) {
    $age = Answer::where('body', $age)->first()->id;
    $endResultIds = TagEndResult::where('tag', 'pa'. $age)->pluck('end_result_id');
    $results = EndResult::whereIn('id', $endResultIds)->get();

    return view('admin.end_results.list', compact('results'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @param \Kris\LaravelFormBuilder\FormBuilder $formBuilder
   *
   * @return \Illuminate\Http\Response
   */
  public function create(KFB $formBuilder) {
    //
    $form = $formBuilder->create('App\Forms\EndResultForm', [
      'method' => 'POST',
      'url'    => route('admin.results.store'),
    ]);

    return view('admin.end_results.create', compact('form'));
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param \Illuminate\Http\Request|Request $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request) {
    // pg personal gender'
    if($request->get('gender')) {
      $gender = 'pg' . $request->get('gender');
    }

    if($request->get('age')) {
      // pa personal age
      $age = 'pa' . $request->get('age');
    }

    $end_result_message = EndResult::create($request->all());

    $states = (array) $request->get('tags');

    $new_states = [];
    foreach ($states as $index => $state) {
      $new_states[] = [
        'end_result_id' => $end_result_message->id,
        // st state
        'tag'           => 'st' . $state,
        'created_at'    => Carbon::now(),
        'updated_at'    => Carbon::now(),
      ];
    }

    $age_gender = [];
    $time = Carbon::now();

    if(isset($gender))
      $age_gender[] = [
        'end_result_id' => $end_result_message->id,
        'tag'           => $gender,
        'created_at'    => $time,
        'updated_at'    => $time,
      ];
    if(isset($age))
      $age_gender[] = [
        'end_result_id' => $end_result_message->id,
        'tag'           => $age,
        'created_at'    => $time,
        'updated_at'    => $time,
      ];

    $tag_end_result_values = array_merge($age_gender, $new_states);

    TagEndResult::insert($tag_end_result_values);

    return redirect()->back();
//    return redirect()->route('admin.results.products.index', $end_result_message);
  }

  /**
   * Display the specified resource.
   *
   * @param \App\Question $question
   *
   * @return \Illuminate\Http\Response
   * @internal param int $id
   */
  public function show(Question $question) {
    return $question->state->name;
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param \App\EndResult                       $endResult
   * @param \Kris\LaravelFormBuilder\FormBuilder $formBuilder
   *
   * @return \Illuminate\Http\Response
   * @internal param \App\Question $question
   * @internal param int $id
   */
  public function edit(EndResult $endResult, KFB $formBuilder) {
//    dd($endResult->tags);
    $form = $formBuilder->create('App\Forms\EndResultForm', [
      'method' => 'PATCH',
      'url'    => route('admin.results.update', $endResult),
      'model'  => $endResult,
    ]);

    // gender field
    $gender_tag = $endResult->tags()->where('tag', 'like', 'pg%')->first();

    $gender = '';
    if($gender_tag) {
      $gender = $gender_tag->tag;
    }

    $form->modify('gender', 'select', [
      'selected' => str_replace('pg', '', $gender),
    ]);

    // age field
    $age_tag = $endResult->tags()->where('tag', 'like', 'pa%')->first();

    $age = '';
    if($age_tag) {
      $age = $age_tag->tag;
    }

    $form->modify('age', 'select', [
      'selected' => str_replace('pa', '', $age),
    ]);

    // tags field
    $states_tag = $endResult->tags()->where('tag', 'like', 'st%')->pluck('tag');

    $states = [];
    if($states_tag) {
      foreach ($states_tag as $state_tag) {
        $states[] = str_replace('st', '', $state_tag);
      }
    }

    $form->modify('tags', 'select', [
      'selected' => $states,
    ]);

    $form->modify('submit', 'submit', [
      'label' => 'ویرایش',
    ]);

    return view('admin.end_results.create', compact('form'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request $request
   * @param \App\EndResult            $endResult
   *
   * @return \Illuminate\Http\Response
   * @internal param \App\Question $question
   *
   * @internal param int $id
   */
  public function update(Request $request, EndResult $endResult) {
    // pg personal gender'
    if($request->get('gender')) {
      $gender = 'pg' . $request->get('gender');
    }

    if($request->get('age')) {
      // pa personal age
      $age = 'pa' . $request->get('age');
    }

    $states = (array) $request->get('tags');

    $new_states = [];
    foreach ($states as $index => $state) {
      $new_states[] = [
       'end_result_id' => $endResult->id,
       // st state
       'tag'           => 'st' . $state,
       'created_at'    => Carbon::now(),
       'updated_at'    => Carbon::now(),
      ];
    }

    $age_gender = [];
    $time = Carbon::now();

    if(isset($gender))
      $age_gender[] = [
       'end_result_id' => $endResult->id,
       'tag'           => $gender,
       'created_at'    => $time,
       'updated_at'    => $time,
      ];
    if(isset($age))
      $age_gender[] = [
       'end_result_id' => $endResult->id,
       'tag'           => $age,
       'created_at'    => $time,
       'updated_at'    => $time,
      ];

    $tag_end_result_values = array_merge($age_gender, $new_states);

    $parameter = compact('tag_end_result_values', 'endResult');
    DB::transaction(function () use ($parameter) {
      $endResult = $parameter['endResult'];
      $tag_end_result_values = $parameter['tag_end_result_values'];
      DB::table('tag_end_result')->where('end_result_id', '=', $endResult->id)->delete();
      TagEndResult::insert($tag_end_result_values);
    });

    return redirect()->back();
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param \App\EndResult $endResult
   *
   * @return \Illuminate\Http\Response
   * @internal param \App\Question $question
   *
   * @internal param int $id
   */
  public function destroy(EndResult $endResult) {

    // TODO:: this destroy method must change to Foreign key cascading delete. in tag_end_result, customer_end_result, related_products tables?
    DB::transaction(function () use ($endResult) {
      // tag_end_result -> end_result_id
      TagEndResult::destroy(TagEndResult::where('end_result_id', $endResult->id)
                                        ->pluck('id')
                                        ->toArray());
      // customer_end_result -> end_result_id
      CustomerEndResult::destroy(CustomerEndResult::where('end_result_id', $endResult->id)
                                                  ->pluck('id')
                                                  ->toArray());
      // related_products -> end_result_id
      RelatedProduct::destroy(RelatedProduct::where('end_result_id', $endResult->id)
                                            ->pluck('id')
                                            ->toArray());

      // delete end result
      EndResult::destroy($endResult->id);

    });

    return 1;
  }
}

resources/views/admin/end_results/create.blade.php
@extends('admin.default')

@section('content')
    <div class="main-content" autoscroll="true" bs-affix-target="" init-ripples="" style="">
        <div class="col-md-10 col-md-push-1">
            <div class="well white">
                {!! form($form) !!}
            </div>
            <a href="{{ route('admin.questions.index') }}" class="btn btn-lg btn-round btn-primary pull-left">
                <span class="md md-keyboard-arrow-left"></span>
            </a>
        </div>
    </div>
@endsection

resources/views/admin/end_results/group-list.blade.php
@extends('admin.default')

@section('content')
    <div class="main-content" autoscroll="true" bs-affix-target="" init-ripples="" style="">
        <section class="tables-data">
            <div class="page-header">
                <h1>Diagnostic Order by Age</h1>
            </div>
            <div class="card">
                <div>
                    <div class="">
                        <table class="table table-full table-full-small">
                            <thead>
                            <tr>
                                <th>سن</th>
                                <th>مشاهده تشخیص ها</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($answers as $answer)
                                <tr class="deletable">
                                    <td>
                                        {{ $answer->body }}
                                    </td>
                                    <td>
                                        <a href="{{ action('EndResultController@resultsOnAge', $answer->body) }}"
                                           title="لیست تشخیص ها" class="btn btn-lg btn-round btn-info">
                                            <span class="md md-list"></span>
                                            <div class="ripple-wrapper"></div>
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
        <div class="footer-buttons">
            <a href="{{route('admin.results.create')}}"
               class="btn btn-primary btn-round btn-lg" data-title="تشخیص"
               data-toggle="tooltip" data-original-title="" title="">
                <i class="md md-add"></i>
            </a>
        </div>
    </div>
@endsection

resources/views/admin/end_results/list.blade.php
@extends('admin.default')

@section('content')
    <div class="main-content" autoscroll="true" bs-affix-target="" init-ripples="" style="">
        <section class="tables-data">
            <div class="page-header">
                <h1>
                    {{--<i class="md md-add-circle-outline"></i>--}}
                    <a href="{{route('admin.results.create')}}" class="md md-add-circle-outline text-primary">Add
                        Diagnostic</a>
                </h1>
            </div>
            <div class="card">
                <div>
                    <div class="">
                        <table class="table table-full table-full-small">
                            <thead>
                            <tr>
                                <th>پیغام به کاربر</th>
                                <th>ویژگی ها</th>
                                <th>تنظیمات</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($results as $index => $result)
                                <?php $tags = [] ?>
                                <tr class="deletable">
                                    <td>{{ $result->body }} </td>
                                    @foreach($result->tags as $tag)
                                        <?php $bare_tag = str_replace(['pg', 'pa', 'st'], '', $tag->tag) ?>
                                        @if(starts_with($tag->tag, 'pg'))
                                            <?php $tags[] = $bare_tag ? 'مرد' : 'زن'  ?>
                                        @elseif(starts_with($tag->tag, 'pa'))
                                            <?php $tags[] = App\Answer::find($bare_tag)->body ?>
                                        @else
                                            <?php $tags[] = App\State::find($bare_tag)['name'] ?>
                                        @endif
                                    @endforeach
                                    <td>{{ implode(', ', $tags) }}</td>
                                    <td>
                                        <a href="{{ route('admin.results.edit', $result) }}"
                                           class="btn btn-lg btn-round btn-success">
                                            <span class="md md-mode-edit"></span>

                                            <div class="ripple-wrapper"></div>
                                        </a>
                                        <a href="{{ route('admin.results.destroy', $result) }}"
                                           class="btn btn-lg btn-round btn-success item delete">
                                            <span class="md md-delete"></span>

                                            <div class="ripple-wrapper"></div>
                                        </a>
                                        <a href="{{ route('admin.results.products.index', $result) }}"
                                           title="لیست محصولات مرتبط" class="btn btn-lg btn-round btn-info">
                                            <span class="md md-list"></span>

                                            <div class="ripple-wrapper"></div>
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
        <div class="footer-buttons">
            <a href="{{route('admin.results.create')}}"
               class="btn btn-primary btn-round btn-lg" data-title="تشخیص"
               data-toggle="tooltip" data-original-title="" title="">
                <i class="md md-add"></i>
            </a>
        </div>
    </div>
@endsection